spring:
#  redis:
#    database: 1
#    host: localhost
#    password: 123456
#    port: 6379
#    timeout: 10000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: movie
    password: movie
    url: jdbc:mysql://mysql.huazai.vip:3306/movie?allowMultiQueries=true

redis:
  maxIdle: 300
  maxTotal: 1000
  maxWaitMillis: 10000
  minEvictableIdleTimeMillis: 300000
  numTestsPerEvictionRun: 1024
  testOnBorrow: true
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 30000