logging:
  level:
    team:
      software:
        mapper: debug
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: team.software.bean
server:
  port: 8082
spring:
  application:
    name: spider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: movie
    url: jdbc:mysql://mysql.huazai.vip/movie?allowMultiQueries=true
    username: movie

pagehelper:
  helper-dialect: mysql
  page-size-zero: false
  reasonable: true
  support-methods-arguments: true













